
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}-{branch}'

# branches to build
branches:
  # whitelist
  only:
    - develop
    - release
    - default

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: c:\projects\vpo2

# set clone depth
clone_depth: 1                       # clone entire repository history if not defined

# fetch repository as zip archive
shallow_clone: false                 # default is "false"

environment:
  PFX_PASSW:
    secure: ifE3wBjV66koJF1uPVbfHQ==
  PFX7z_PASSW:
    secure: V31OHD0fr3vqkXWndDanbw==
  PFX_FILE: C:\projects\vpo2\SeamlySert.pfx
  matrix:
  - QT5: Qt\5.9\mingw53_32
    QT_VERSION: Qt5.9
    QMAKE_GENERATOR: "MinGW Makefiles"
    MINGW_PATH: C:\Qt\Tools\mingw530_32\bin
    PLATFORM: x86
    DEPLOY: true
  - QT5: Qt\5.9\msvc2015_64
    QMAKE_GENERATOR: "NMake Makefiles JOM"
    VSVER: 14
    PLATFORM: x64
    DEPLOY: false
  - QT5: Qt\5.9\msvc2015
    QMAKE_GENERATOR: "NMake Makefiles JOM"
    VSVER: 14
    PLATFORM: x86
    DEPLOY: false

# scripts that are called at very beginning, before repo cloning
init:
  # Path before 
  - path
  - set QTDIR=C:\%QT5%
  - set PATH=C:\ProgramData\chocolatey;%QTDIR%\bin;%QTDIR%\include;C:\Tools\PsTools;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0\
  - set PATH=%PATH%;C:\Program Files\Git\cmd\
  - set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\
   set PATH=%PATH%;C:\Program Files\7-Zip\
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - if NOT "%QMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - if "%QMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using MinGW"
  # Set VC variables for the platform
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if %PLATFORM% == x64 call "%VSCOMNTOOLS%\..\..\VC\bin\x86_amd64\vcvarsx86_amd64.bat"
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if %PLATFORM% == x86 call "%VSCOMNTOOLS%\..\..\VC\bin\vcvars32.bat"
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "x86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "x64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - if "%QMAKE_GENERATOR%" == "MinGW Makefiles" set PATH=%MINGW_PATH%;%PATH%
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
  - set PATH=C:\projects\vpo2\build\src\libs\vpropertyexplorer\bin;C:\projects\vpo2\build\src\libs\qmuparser\bin;%PATH%
  # Path after
  - path
  - qmake -v
 
install:
  - choco install -y InnoSetup  
  
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - 7z x C:\projects\vpo2\seamly.7z -p%PFX7z_PASSW% 
  - cd c:\projects\vpo2 
  - md build

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd build
  - if "%DEPLOY%" == "true" (qmake ..\Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=checkWarnings) else (qmake ..\Seamly2D.pro -r CONFIG+=noDebugSymbols CONFIG+=no_ccache CONFIG+=checkWarnings)
  - if not "%QMAKE_GENERATOR%" == "MinGW Makefiles" (nmake -s) else (mingw32-make -j%NUMBER_OF_PROCESSORS%)

# to run your custom scripts instead of automatic tests
test_script:
  - if "%QMAKE_GENERATOR%" == "MinGW Makefiles" (mingw32-make -s check TESTARGS="-silent")

# to disable automatic tests 
#test: off

matrix:
  fast_finish: false

#---------------------------------#
#         notifications           #
#---------------------------------#
  
notifications:
# Email
  - provider: Email
    to:
      - dvajdual@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

#---------------------------------#
#         deployment              #
#---------------------------------#

# prepare to deploy
after_test:
  - if "%DEPLOY%" == "true" (mingw32-make install)
  - signtool sign /debug /f %PFX_FILE% /p %PFX_PASSW% build/package/seamly2d_*.exe
  - signtool timestamp /t http://timestamp.verisign.com/scripts/timestamp.dll build/package/seamly2d_*.exe

artifacts:
  - path: build/package/seamly2d_*.exe
    name: seamly2d-win-$(QT_VERSION)-$(APPVEYOR_REPO_COMMIT)

deploy:
- provider: BinTray
  username: slspencer
  api_key:
    secure: xnl+xCbtLd5ACm3NM9wJylajIGRJ59JvmZSz5M4bLn2Elw9d6H2sTa8XXGZTgZw+
  subject: fashionfreedom
  repo: Seamly2D
  package: Seamly2D-win_auto-upload
  publish: true
  override: true
  version: 0.6
  on:
    DEPLOY: true
  artifact: seamly2d-win-$(QT_VERSION)-$(APPVEYOR_REPO_COMMIT)
