
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

##KimMF workaround VS2017 Build Issues #1761 in Microsoft/visualfsharp 8-6-18 
 

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}-{branch}'

# branches to build
branches:
  # whitelist
  only:
    - develop
##KimMF 8-6-18
##    - release
##    - default

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
# updated 10/25/2018 slspencer -- replaced vpo2 with seamly2d
clone_folder: c:\projects\seamly2d

# set clone depth
clone_depth: 1                       # clone entire repository history if not defined

# fetch repository as zip archive
shallow_clone: false                 # default is "false"

environment:
  PFX_PASSW:
    secure: f4vku3+mgQ57n7SBkfB7Ag==
  PFX7z_PASSW:
    # updated 10/25/2018 slspencer -- replaced V31OHD0fr3vqkXWndDanbw== with Seamly2D
    secure: Seamly2D
  #updated 10/25/2018 slspencer -- replaced vpo2\SeamlySert.pfx with seamly2d\Seamly2D.pfx
  PFX_FILE: C:\projects\seamly2d\Seamly2D.pfx
  matrix:
  - QT5: Qt\5.9\mingw53_32
    QT_VERSION: Qt5.9
    QMAKE_GENERATOR: "MinGW Makefiles"
    MINGW_PATH: C:\Qt\Tools\mingw530_32\bin
    PLATFORM: x86
    DEPLOY: true
  - QT5: Qt\5.9\msvc2015_64
    QMAKE_GENERATOR: "NMake Makefiles JOM"
    VSVER: 14
    PLATFORM: x64
    DEPLOY: false
  - QT5: Qt\5.9\msvc2015
    QMAKE_GENERATOR: "NMake Makefiles JOM"
    VSVER: 14
    PLATFORM: x86
    DEPLOY: false

# scripts that are called at very beginning, before repo cloning
init:
  # Path before 
  - path
  - set QTDIR=C:\%QT5%
  - set PATH=C:\ProgramData\chocolatey;%QTDIR%\bin;%QTDIR%\include;C:\Tools\PsTools;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0\
  - set PATH=%PATH%;C:\Program Files\Git\cmd\
  - set PATH=%PATH%;C:\Program Files\7-Zip\
  
 ##KimMF 8-6-18
  - ps: $env:VSCOMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\" 
 ### - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - if NOT "%QMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - if "%QMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using MinGW"
  # Set VC variables for the platform
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if %PLATFORM% == x64 call "%VSCOMNTOOLS%\..\..\VC\bin\x86_amd64\vcvarsx86_amd64.bat"
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if %PLATFORM% == x86 call "%VSCOMNTOOLS%\..\..\VC\bin\vcvars32.bat"
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "x86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" if "%PLATFORM%" == "x64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - if "%QMAKE_GENERATOR%" == "MinGW Makefiles" set PATH=%MINGW_PATH%;%PATH%
  - if "%QMAKE_GENERATOR%" == "NMake Makefiles JOM" set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
  # updated 10/25/2018 slspencer -- replaced vpo2 with seamly2d
  - set PATH=C:\projects\seamly2d\build\src\libs\vpropertyexplorer\bin;C:\projects\seamly2d\build\src\libs\qmuparser\bin;%PATH%
  # Path after
  - path
  - qmake -v
 
install:
  - choco install -y InnoSetup  
  
  
#---------------------------------#
#       build configuration       #
#---------------------------------#
#updated 10/25/2018 slspencer -- replaced vpo2 with seamly2d
before_build:
  - 7z x C:\projects\seamly2d\seamly.7z -p%PFX7z_PASSW%
  - cd c:\projects\seamly2d
  - md build

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd build
  - if "%DEPLOY%" == "true" (qmake ..\Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=checkWarnings) else (qmake ..\Seamly2D.pro -r CONFIG+=noDebugSymbols CONFIG+=no_ccache CONFIG+=checkWarnings)
  - if not "%QMAKE_GENERATOR%" == "MinGW Makefiles" (nmake -s) else (mingw32-make -j%NUMBER_OF_PROCESSORS%)

# to run your custom scripts instead of automatic tests
test_script:
  - if "%QMAKE_GENERATOR%" == "MinGW Makefiles" (mingw32-make -s check TESTARGS="-silent")

# to disable automatic tests 
#test: off

matrix:
  fast_finish: false

#---------------------------------#
#         notifications           #
#---------------------------------#
  
notifications:
# Email
# updated 10/25/2018 -- replaced dvajdual@gmail.com with susan.spencer@gmail.com
  - provider: Email
    to:
      - susan.spencer@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

#---------------------------------#
#         deployment              #
#---------------------------------#

# prepare to deploy
# updated 10/25/2018 slspencer -- replaced vpo2 with seamly2d
after_test:
  - if "%DEPLOY%" == "true" (mingw32-make install)
  - if "%DEPLOY%" == "true" cd "C:\Program Files (x86)\Windows Kits\8.1\bin\x86"  
  - if "%DEPLOY%" == "true" signtool sign /f %PFX_FILE% /p %PFX_PASSW%  /t http://timestamp.comodoca.com /v c:/projects/seamly2d/build/package/seamly2d_*.exe
  - if "%DEPLOY%" == "true" signtool sign /f %PFX_FILE% /p %PFX_PASSW% /fd sha256 /tr http://timestamp.comodoca.com/?td=sha256 /td sha256 /as /v c:/projects/seamly2d/build/package/seamly2d_*.exe  
  - if "%DEPLOY%" == "true" for %%I in (c:\projects\seamly2d\build\package\seamly2d_*.exe) do set artifactName=%%~nI
  - if "%DEPLOY%" == "true" 7z a -tzip -mx1 c:\projects\seamly2d\build\package\%artifactName%.zip c:\projects\seamly2d\build\package\seamly2d_*.exe

artifacts:
  - path: build/package/seamly2d_*.zip
    name: seamly2d-win-$(QT_VERSION)-$(APPVEYOR_REPO_COMMIT)

deploy:
- provider: BinTray
  username: slspencer
  api_key:
    secure: xnl+xCbtLd5ACm3NM9wJylajIGRJ59JvmZSz5M4bLn2Elw9d6H2sTa8XXGZTgZw+
  subject: fashionfreedom
  repo: Seamly2D
  package: Seamly2D-win_auto-upload
  publish: true
  override: true
  version: 0.6.0.1
  on:
    DEPLOY: true
    branch: develop
  artifact: seamly2d-win-$(QT_VERSION)-$(APPVEYOR_REPO_COMMIT)
  
- provider: BinTray
  username: slspencer
  api_key:
    secure: xnl+xCbtLd5ACm3NM9wJylajIGRJ59JvmZSz5M4bLn2Elw9d6H2sTa8XXGZTgZw+
  subject: fashionfreedom
  repo: Seamly2D
  package: Seamly2D-win_release
  publish: true
  override: true
  version: 0.6.0.1
  on:
    DEPLOY: true
    branch: master
  artifact: seamly2d-win-$(QT_VERSION)-$(APPVEYOR_REPO_COMMIT)  
